version: '3.7'

services:

 d0490-hom:
    image: repo.ms.gov.br/sgi/csis/g14/d0490.hom.consulta-edoc-elastic:1.0.10
    networks:
      - proxy_net
    environment:
      sid: D0490
      app_name: consulta-edoc-elastic
      app_version: 1.0.10
      NODE_ENV: hom
    deploy:
      resources:
        limits:
          memory: 700M
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
      placement:
        constraints:
          - node.labels.region == hom
      labels:
        - "traefik.frontend.entryPoints=http"
        - "traefik.port=5000"
        - "traefik.backend=d0490-hom-consulta-edoc-elastic"
        - "traefik.frontend.rule=Host: hom.api.sgi.ms.gov.br;PathPrefix:/d0490/consulta-edoc-elastic/v1"
        - "traefik.docker.network=proxy_net"
networks:
  proxy_net:
    external: true