const OK = 200
const SERVICE_UNAVAILABLE = 503
const BAD_REQUEST = 400
const NO_LIVING_CONNECTION = 444
const INTERNAL_SERVER_ERROR = 500

module.exports = { OK, SERVICE_UNAVAILABLE, BAD_REQUEST, NO_LIVING_CONNECTION, INTERNAL_SERVER_ERROR }